# This Config Controls what plugins work on certain worlds.
# Example
# limit:
#   WorldEdit:
#     - world
#     - world_nether
#   Essentials: []
# This will make it so worldedit will only work in world & world_nether, meaning in the end it is not usable.
# When there is no worlds in the list it will allow it for any worlds, in this example allowing all worlds.
# Whenever a plugin is added, this config will automatically add it!
# exempt-login-events is for excluding login events when true, this means if a plugin uses PlayerLogin it will allow it for any world. We advise this to be enabled!
exempt-login-events: true
blocked-msg: '&4[Error] This command cannot be performed in this world.'
limit: {}